apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: multi-region-app
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - multi-region
  selector:
    matchLabels:
      app: multi-region-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
